[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
# startup_mode = "Maximized"
dimensions = { columns = 150, lines = 40 }
title = "shell"
decorations_theme_variant = "Dark"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "Fira Code", style = "Regular" }
# normal = { family = "Hack", style = "Regular" }
# normal = { family = "Source Code Pro", style = "Regular" }
# normal = { family = "IBM Plex Mono", style = "Regular" }
# normal = { family = "Jetbrains Mono", style = "Regular" }
size = 16
offset = { x = 0, y = 0 }

[terminal]
shell = { program = "/usr/bin/fish" }

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
