[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 17
offset = { x = 0, y = 0 } 

[terminal]
shell = "/bin/fish"
