[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = "red"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "yellow"
underline = false
bold = true
italic = false

[style.example_code]
foreground = "white"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "white"
underline = false
bold = false
italic = false

[display]
compact = true
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720
pages_url = "https://tldr-pages.github.io/tldr/pages.zip"

[directories]
cache_dir = "/home/phydon/.cache/tealdeer"
