format = """
$status\
$battery\
$sudo\
$username\
$hostname\
$git_status\
$directory\
$shell\
$character
"""

palette = "lav"

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[palettes.lav]
purple = "#7F6FDB"
dark_purple = "#743ABF"
bright_magenta = "#CC3980"
dark_blue = "#706EFF"
bright_green = "#3BB38C"

[status]
disabled = false
symbol = ""
style = "red"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
style = "fg:#808EA5"

[battery]  
disabled = false
full_symbol = ""
unknown_symbol = "❔"
empty_symbol = "☠️"
# full_symbol = ""
# charging_symbol = ""
# unknown_symbol = ""
# empty_symbol = ""
[[battery.display]] 
threshold = 25
style = "red"
discharging_symbol = "☠️"
charging_symbol = "🗲"
# discharging_symbol = ""
[[battery.display]] 
threshold = 35
style = "bright_magenta"
discharging_symbol = "↘"
charging_symbol = "🗲"
# discharging_symbol = ""
[[battery.display]]
threshold = 99
style = "bright_green"
charging_symbol = "🗲"
discharging_symbol = "↘"
# discharging_symbol = ""

[c]  
format = '\[[ ($version(-$name))]($style)\]'
# style = "bold fg:#8F670B"
style = "fg:#808EA5"

[character]  
disabled = true
# success_symbol = "[-I❯](bold green dimmed)"
# success_symbol = "[:❯](bold dimmed fg:#4C74A6)"
# error_symbol = "[:❯](bold fg:#870000)"
# vicmd_symbol = "[::❯](bold fg:#b58900) "
# success_symbol = "[:](bold fg:#B2C1D6)"
# error_symbol = "[:](bold fg:#d32c5d)"
# vicmd_symbol = "[::](bold fg:#b58900) "
success_symbol = "[:](bold dark_purple)"
error_symbol = "[:](bold dark_purple)"
vicmd_symbol = "[::](bold dark_purple) "

[cmake]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[cmd_duration]  
format = '\[[took $duration]($style)\]'
# format = '\[[⏱ $duration]($style)\]'
# style = "bold fg:#8F670B"
# style = "fg:#4e4e4e"
style = "fg:#808EA5"

[cobol]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[conda]
format = '\[[$symbol$environment]($style)\]'
style = "fg:#808EA5"

[crystal]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

# [daml]
# format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[deno]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[directory]  
read_only = "  "
read_only_style = "red"
truncation_length = 3
truncation_symbol = ".."
truncate_to_repo = false
home_symbol = "~"
# style = "fg:#4e4e4e"
# style = "fg:#808EA5"
style = "purple"

[docker_context]
format = '\[[ $context]($style)\]'
style = "fg:#808EA5"

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
style = "fg:#808EA5"

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
style = "fg:#808EA5"

[elm]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[erlang]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
style = "fg:#808EA5"

[git_branch]  
format = '\[[git $branch]($style)\]'
style = "fg:#808EA5"

[git_status]  
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "dark_blue"

[golang]  
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[haskell]
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[helm]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
style = "fg:#808EA5"

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.'
disabled = false

[java]  
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[julia]  
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[kotlin]  
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'
style = "fg:#808EA5"

[lua]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[memory_usage]  
disabled = true
format = '\[ [$ram_pct(|$swap_pct)]($style)\]'
threshold = -1
# style = "bold dimmed red"
style = "bold fg:#5e0b0f"

[nim]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
style = "fg:#808EA5"

[nodejs]
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
style = "fg:#808EA5"

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'
style = "fg:#808EA5"

[package]  
# format = '\[[$symbol$version]($style)\]'
format = '\[[pkg $version]($style)\]'
style = "fg:#808EA5"

[perl]  
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[php]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[pulumi]
format = '\[[$symbol$stack]($style)\]'
style = "fg:#808EA5"

[purescript]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[python]  
# format = '\[[ ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
format = '\[[ ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "fg:#808EA5"

[red]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[ruby]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[rust]  
format = '\[[ ($version)]($style)\]'
style = "fg:#808EA5"

[scala]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[shell]
format = "[$indicator]($style)"
fish_indicator = "fish"
powershell_indicator = "psh"
bash_indicator = "bash"
zsh_indicator = "zsh"
nu_indicator = "nu"
cmd_indicator = "cmd"
ion_indicator = "ion"
elvish_indicator = "esh"
tcsh_indicator = "tsh"
xonsh_indicator = "xsh"
unknown_indicator = "unknown shell"
style = "bold fg:#B2C1D6"
# style = "bold fg:#8b2252"
# style = "bold fg:#4C74A6"
# style = "bold fg:#49A699"
# style = "bold fg:#4e4e4e"
# symbol _
disabled = true

[spack]
format = '\[[$symbol$environment]($style)\]'
style = "fg:#808EA5"

[sudo]  
format = '\[[as sudo](&style)\]'
allow_windows = true
disabled = false

[swift]  
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[terraform]
format = '\[[$symbol$workspace]($style)\]'
style = "fg:#808EA5"

[time]
format = '\[[$time]($style)\]'
style = "fg:#808EA5"

[username]
format = '\[[$user]($style)\] '
style_root = "bold red"
style_user = "bold white"
show_always = false
disabled = false

[vagrant]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[vlang]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

[zig]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#808EA5"

