[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[battery]  
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
unknown_symbol = ""
empty_symbol = ""
disabled = false
[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 25%
threshold = 25
style = "bold red"
discharging_symbol = ""
[[battery.display]] # "bold yellow" style and   symbol when capacity is between 25% and 35%
threshold = 35
style = "bold yellow"
discharging_symbol = ""
[[battery.display]]
threshold = 99
style = "bold green"
discharging_symbol = ""

[c]  
format = '\[[ ($version(-$name))]($style)\]'

[character]  
success_symbol = "[-I❯](bold green)"
error_symbol = "[-I❯](bold red)"
vicmd_symbol = "[-N❯](bold bright-yellow) "

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]  
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

# [daml]
# format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[directory]  
read_only = " "
read_only_style = "red"
truncation_symbol = ".."
home_symbol = "~"

[docker_context]
format = '\[[ $context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]  
format = '\[[git $branch]($style)\]'

[git_status]  
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]  
format = '\[[ ($version)]($style)\]'

[haskell]
format = '\[[ ($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]  
format = '\[[ ($version)]($style)\]'

[julia]  
format = '\[[ ($version)]($style)\]'

[kotlin]  
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]  
disabled = false
format = '\[ [$ram_pct(|$swap_pct)]($style)\]'
threshold = -1
style = "bold dimmed red"

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[ ($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]  
format = '\[[$symbol$version]($style)\]'

[perl]  
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]  
format = '\[[ ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]  
format = '\[[ ($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[shell]
format = "[$indicator]($style) "
fish_indicator = "fish"
powershell_indicator = "psh"
bash_indicator = "bash"
zsh_indicator = "zsh"
nu_indicator = "nushell"
cmd_indicator = "cmd"
ion_indicator = "ion"
elvish_indicator = "esh"
tcsh_indicator = "tsh"
xonsh_indicator = "xsh"
unknown_indicator = "unknown shell"
style = "green dimmed bold"
disabled = false
# symbol _

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]  
format = '\[[as sudo](&style)\]'
disabled = true

[swift]  
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
