# theme = "walker"
# theme = "kaolin-dark"
# theme = "mellow"
theme = "serika-darker"
# theme = "ttoxed"
# theme = "gruber-darker"

[editor]
line-number = "relative"
color-modes = true
shell = ["powershell", "-c"]
auto-completion = true
completion-trigger-len = 2
auto-format = true
auto-info = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "spacer", "spacer", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["selections", "primary-selection-length"]
right = ["total-line-numbers", "position", "position-percentage", "spacer", "register", "spacer", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40
wrap-indicator = "↪"  # set wrap-indicator to "" to hide it

[editor.smart-tab]
enable = false

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.space]
w = { w = ":open 'G:/Meine Ablage/Obsidian/Main/Quicknotes.md'" }
r = ":reflow"
u = "switch_to_lowercase"
U = "switch_to_uppercase"
C-k = "kill_to_line_end"
C-u = "kill_to_line_start"
C-c = ":run-shell-command Cargo check"
C-r = ":run-shell-command Cargo run"

[keys.insert.q]
q = "normal_mode"

[keys.select.q]
q = "normal_mode"

[keys.select.space]
u = "switch_to_lowercase"
U = "switch_to_uppercase"
