theme = "lavendel"

[editor]
line-number = "relative"
color-modes = true
# shell = "nushell"
auto-completion = true
completion-trigger-len = 2
auto-format = true
auto-info = true
# bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
# right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.space]
w = { w = ":open ~/obsidian_vault/quicknotes.md" }
r = ":reflow"
u = "switch_to_lowercase"
U = "switch_to_uppercase"

[keys.insert.q]
q = "normal_mode"

[keys.select.q]
q = "normal_mode"

[keys.select.space]
u = "switch_to_lowercase"
U = "switch_to_uppercase"
