theme = "gruberdarker"

[editor]
line-number = "relative"
color-modes = true
# shell = "nushell"
auto-completion = true
completion-trigger-len = 2
auto-format = true
auto-info = true
# bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
# right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
"space" = { w = { w = ":open ~/obsidian_vault/quicknotes.md" } }

[keys.insert]
q = { q = "normal_mode" }

[keys.select]
q = { q = "normal_mode" }
