[[language]]
name = "rust"
# https://rust-analyzer.github.io/manual.html#configuration
diagnostic-severity = "warning"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
config = {format = {"rust-analyzer.rustfmt.extraArgs" = "max_width=80"}}

[[language]]
name = "python"
scope = "source.python"
# INFO py -m pip install python-lsp-server python-lsp-ruff
language-servers = ["pylsp"]

# INFO use 'black' as the python formatter
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
diagnostic-severity = "warning"

# INFO disable everything from 'pylsp' except for 'ruff'
[language-server.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["W293"], lineLength = 80, cache-dir = "~/.cache/ruff", config = "~/AppData/Roaming/helix/pyproject.toml" }


[[language]]
name = "nu"
shebangs = ["nu"]
indent =  {tab-width = 4, unit = "    "}
diagnostic-severity = "warning"

[[language]]
name = "markdown"
indent =  {tab-width = 4, unit = "    "}
diagnostic-severity = "warning"

[[language]]
name = "c"
indent =  {tab-width = 4, unit = "    "}
diagnostic-severity = "warning"

[[language]]
name = "cpp"
indent =  {tab-width = 4, unit = "    "}
diagnostic-severity = "warning"

[[language]]
name = "toml"
indent =  {tab-width = 4, unit = "    "}
diagnostic-severity = "warning"
