"attribute"                 = "steel1"
"keyword"                   = { fg = "red", modifiers = ["bold"] }
"keyword.directive"         = "lred"
"namespace"                 = "steel1"
"label"                     = "steel1"
"module"                    = "steel1"
"punctuation"               = "steel1"
"punctuation.delimiter"     = "steel1"
"operator"                  = { fg = "steel1", modifiers = ["bold"] }
"special"                   = "steel1"
"variable.other.member"     = "steel2"
"variable"                  = "steel1"
"variable.parameter"        = "steel2"
"type"                      = "steel2"
"type.builtin"              = { fg = "steel2", modifiers = ["bold"] }
"constructor"               = "steel3"
"function"                  = "steel3"
"function.macro"            = { fg = "steel3", modifiers = ["bold"] }
"function.builtin"          = { fg = "steel3", modifiers = ["bold"] }
"comment"                   = { fg = "dgrey", modifiers = ["italic"] }
"variable.builtin"          = "steel1"
"constant"                  = "steel4"
"constant.builtin"          = "steel4"
"string"                    = "steel6"
"constant.numeric"          = "steel5"
"constant.character.escape" = { fg = "steel1", modifiers = ["bold"] }

"markup.heading"            = "viridian"
"markup.list"               = "steel4"
"markup.bold"               = { fg = "teal_blue", modifiers = ["bold"] }
"markup.italic"             = { modifiers = ["italic"] }
"markup.link.url"           = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text"          = "red"
"markup.quote"              = "eggplant"
"markup.raw"                = "grey"

"diff.plus"                 = "viridian"
"diff.delta"                = "teal_blue"
"diff.minus"                = "violetred"

"ui.background"             = { bg = "base1" }
"ui.linenr"                 = { fg = "base4" }
"ui.linenr.selected"        = { fg = "fg1" }
"ui.cursorline"             = { bg = "base0" }
"ui.statusline"             = { fg = "violetred", bg = "base0" }
"ui.statusline.inactive"    = { fg = "steel4", bg = "base0" }
"ui.popup"                  = { bg = "base2" }
"ui.window"                 = { bg = "base2" }
"ui.help"                   = { bg = "base2", fg = "fg1" }

"ui.statusline.normal"      = { fg = "base1", bg = "violetred", modifiers = [ "bold" ]}
"ui.statusline.insert"      = { fg = "base1", bg = "teal_blue", modifiers = [ "bold" ]}
"ui.statusline.select"      = { fg = "base1", bg = "viridian", modifiers = [ "bold" ] }

"ui.text"                   = { fg = "steel6" }
"ui.text.focus"             = { fg = "fg1", modifiers= ["bold"] }
"ui.virtual.lgreyspace"     = "base5"
"ui.virtual.ruler"          = { bg = "base0" }

"ui.selection"              = { bg = "base3" }
"ui.cursor.match"           = { fg = "base3", bg = "grey" }
"ui.cursor"                 = { fg = "base5", modifiers = ["reversed"] }

"ui.menu"                   = { fg = "fg1", bg = "base2" }
"ui.menu.selected"          = { bg = "base3" }

"warning"                   = "lred"
"error"                     = "violetred"
"info"                      = "umber"
"hint"                      = "lgrey"

# make diagnostic underlined, to distinguish with selection text.
diagnostic = { modifiers = ["underlined"] }

[palette]
yellow      = "#dcb659"
lblue       = "#59dcd8"
teal        = "#59dcb7"
teal_blue   = "#2E6170"
blue        = "#36b2d4"
dblue       = "#2E5894"
orange      = "#B7410E"
red         = "#d32c5d"
chocored    = "#700222"
brownred    = "#56223F"
beige  = "#C7A183"
goldbrown   = "#84563B"
brown       = "#996A51"
lbrown      = "#C7A183"
lgreen      = "#7fdc59"
viridian    = "#437066"
eggplant    = "#664864"
lred        = "#dc597f"
purp        = "#780249"
violet      = "#630044"
violetred   = "#8b2252"
dark_cyan   = "#005959"
umber       = "#614D3C"
burgundy    = "#450022"

steel1       = "#5E6C85"
steel2       = "#6F7D95"
steel3       = "#808EA5"
steel4       = "#909FB6"
steel5       = "#A1B0C6"
steel6       = "#B2C1D6"

white       = "#E8E8E8" 
milk        = "#E3D0C1" 
lgrey       = "#A6AEBA" 
grey        = "#536878"
dgrey       = "#565B61" 
 
base0       = "#13181e"
base1       = "#161c23" 
base2       = "#232d38"
base3       = "#313f4e" 
base4       = "#415367" 
base5       = "#abb2bf"
 
fg0         = "#c6b8ad"
fg1         = "#e5ded6"