# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"
  
  # Print the current time
  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
      
  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  - trigger: ":mast"
    replace: "Masterarbeit_Pohl"
  
  # github phydon config files
  - trigger: ":ghcon"
    replace: "https://github.com/Phydon/Config-files"
  
  # email greetings
  - trigger: ":grt"
    replace: "{{greeting}}"
    vars:
      - name: greeting
        type: choice
        params:
          values:
            - "Sehr geehrter Herr Dr. Ezzeldin,\n\n" 
            - "Sehr geehrte Damen und Herren,\n\n" 
            - "Sehr geehrter Herr " 
            - "Sehr geehrte Frau "
  
  # email form
  - trigger: ":mail"
    form: |
      [[choice1]] [[name]],
    
      [[text]]
    
      [[choice2]]
      [[name]]
    form_fields:
      text:
        multiline: true
      choice1:
        type: choice
        values:
          - Hallo
          - Sehr geehrte Frau          
          - Sehr geehrter Herr          
      choice2:
        type: choice
        values:
          - Beste Grüße
          - Liebe Grüße
          - Mit freundlichen Grüßen
          - Mit freundlichen Grüßen / Best Regards
        
  # file picker
  # FIXME
  - trigger: ":file\\((?P<pattern>.*)\\)"
    replace: "{{form1.file}}"
    vars:
      - name: files
        type: shell
        params:
          cmd: "{{find}}"
          # cmd: "sf $env:ESPANSO_PATTERN C:/Users/Pohl -D 1 -fp"
      - name: find
        type: echo
        params:
          echo: "sf $env:ESPANSO_PATTERN C:/Users/Pohl -D 1 -fp"
      - name: form1
        type: form
        params:
          layout: |
            Select file:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
          
  # replacement for TODO
  - triggers: ["# T", "#T"]
    replace: "# TODO "
  
  - triggers: ["// T", "//T"]
    replace: "// TODO "
  
  # replacement for FIXME
  - triggers: ["# F", "#F"]
    replace: "# FIXME "
  
  - triggers: ["// F", "//F"]
    replace: "// FIXME "
