# set default shell
set-option -g default-shell /usr/bin/fish

# remap prefix from 'C-b' to 'C-g'
unbind C-b
set-option -g prefix C-g
bind-key C-g send-prefix

# enable mouse scrolling, clicking and resizing
set -g mouse on

# increase history
set-option -g history-limit 100000

# set first windows and panes to start with one
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# more intuitive split commands
bind l split-window -hc "#{pane_current_path}"
bind j split-window -vc "#{pane_current_path}"

# --- NAVIGATION & SWAPPING ---

# Pane navigation with Alt + hjkl (no prefix needed)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# --- UTILITY ---

# keep current path
bind c new-window -c "#{pane_current_path}"

# resizing
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15
